# Load regular season game logs
reg_logs <- read.csv("NBA-2017-18-Regular-Season-Game-Logs.csv")
reg_logs <- as.data.frame(reg_logs)

# Split game logs by team
teamlogs <- split(reg_logs, reg_logs$TEAM)

#rename variables
colnames(reg_logs)[9] <- "FGPct"
colnames(reg_logs)[10] <- "ThreePtMade"
colnames(reg_logs)[11] <- "ThreePtAtt"
colnames(reg_logs)[12] <- "ThreePtPct"
colnames(reg_logs)[15] <- "FtPct"
colnames(reg_logs)[24] <- "PlusMinus"
colnames(reg_logs)[25] <- "EffFGPct"

# Create a model stepwise
model <- lm(reg_logs$W ~ reg_logs$OREB + reg_logs$FGM + reg_logs$FGA + reg_logs$FGPct + reg_logs$ThreePtMade + reg_logs$ThreePtAtt + reg_logs$ThreePtPct + reg_logs$FTM + reg_logs$FTA + reg_logs$FtPct + reg_logs$DREB + reg_logs$AST + reg_logs$STL + reg_logs$BLK + reg_logs$TOV + reg_logs$PF + reg_logs$EffFGPct, data = reg_logs)

# step backwards model
regular_step_backwards <- step(model)
summary(regular_step_backwards)

# step forwards model
regular_step_forwards<-step(lm(W~1, data = reg_logs), scope = X...~(OREB + FGM + FGA + FGPct + ThreePtMade + ThreePtMade + ThreePtAtt + ThreePtPct + FTM + FTA + FtPct + DREB +AST + STL + BLK + TOV + PF + EffFGPct), direction = "forward")

#checking for normality of residuals
qqnorm(resid(step))
qqline(resid(step))

#checking multicollinearity assumption in the game reg_logs
plot(reg_logs$FGPct ~ reg_logs$EffFGPct)
plot(reg_logs$FGPct ~ reg_logs$FGA)
plot(reg_logs$FGPct ~ reg_logs$FTM)
plot(reg_logs$FGPct ~ reg_logs$FGM)
plot(reg_logs$FGPct ~ reg_logs$ThreePtMade)
plot(reg_logs$FGPct ~ reg_logs$DREB)
plot(reg_logs$FGPct ~ reg_logs$ThreePtPct)
plot(reg_logs$STL ~ reg_logs$BLK)
plot(reg_logs$AST ~ reg_logs$FGM)
plot(reg_logs$OREB ~ reg_logs$DREB)
plot(reg_logs$DREB ~ reg_logs$ThreePtPct)
plot(reg_logs$AST ~ reg_logs$EffFGPct)
plot(reg_logs$AST ~ reg_logs$FGA)
plot(reg_logs$AST ~ reg_logs$FTM)
plot(reg_logs$AST ~ reg_logs$FGM)
plot(reg_logs$AST ~ reg_logs$ThreePtMade)
plot(reg_logs$AST ~ reg_logs$TOV)
plot(reg_logs$PF ~ reg_logs$BLK)
plot(reg_logs$PF ~ reg_logs$STL)
plot(reg_logs$PF ~ reg_logs$DREB)

# Check normality assumption
hist(reg_logs$OREB, breaks = 20)
hist(reg_logs$FGM, breaks = 20)
hist(reg_logs$FGA, breaks = 20)
hist(reg_logs$FGPct, breaks = 20)
hist(reg_logs$ThreePtMade, breaks = 20)
hist(reg_logs$ThreePtAtt, breaks = 20)
hist(reg_logs$FTM, breaks = 20)
hist(reg_logs$FTA, breaks = 20)
hist(reg_logs$FtPct, breaks = 20)
hist(reg_logs$DREB, breaks = 20)
hist(reg_logs$AST, breaks = 20)
hist(reg_logs$STL, breaks = 20)
hist(reg_logs$BLK, breaks = 20)
hist(reg_logs$TOV, breaks = 20)
hist(reg_logs$PF, breaks = 20)
hist(reg_logs$EffFGPct, breaks = 20)

######

# Load 2000-2018 data
data <- read.csv("NBA Seasons 2000-2018.csv", header=TRUE)

# Create model for win percentage
model <- lm(data$W.L.~., data = data)
summary(model)
# compare model to stepwise model 
step <- step(model)
summary(step)

# Run t-test to find if conference affects wins
t.test(data$W.L.~data$Conf)

# Show exact difference with analysis of variance
anova <- aov(data$W.L.~data$Conf)
summary(anova)
TukeyHSD(anova)

# Find if offense has increased over time
# Make "YEAR" categorical
data$YEAR <- factor(data$YEAR)
anova <- aov(data$ORtg~data$YEAR)
summary(anova)
TukeyHSD(anova)

# Initiate lists
total <- list()
results <- list()


# Split data by year
splitYear <- split(data, data$YEAR)

# initialize coefficients
coef <- rep(NA, 19)
coef1 <- rep(NA, 19)
coef2 <- rep(NA, 19)
pval<- rep(NA,19)
pval1<- rep(NA,19)
pval2<- rep(NA,19)
O_Model<- list()
O_Model1 <- list()
O_Model2 <- list()


# Run analysis of variance test for each year to see if conference matters yearly
for (i in 1:19)
{
  # Initialize data fram for each year in loop
  year <- as.data.frame(splitYear[i])

    # Rename vars
  names(year)[1] <- "YEAR"
  names(year)[2] <- "Team"
  names(year)[3] <- "Conf"
  names(year)[7] <- "W.L."
  names(year)[11] <- "MOV"
  names(year)[9] <- "ORtg"
  names(year)[8] <- "NRtg"
  names(year)[10] <- "DRtg"
  names(year)[22] <- "ThreeProp"
  names(year)[24] <- "eFG"


  # Run various analyses of variance (change in aov)
  offense <- aov(year$DRtg ~ year$Conf)
  total[i] <- TukeyHSD(offense)
  results$diff[i] <- total[[i]][1]
  results$pval[i] <- total[[i]][4]
  
  # using intercept free lm model to compare predictor importance each year
  
  # offensive rating
  O_Model <- lm(year$W.L~ -1 + year$ORtg)
  coef[i] <- summary(O_Model)$coefficients[1]
  pval[i] <- summary(O_Model)$coefficients[1,4]
  
  # three point proportion
  O_Model1 <- lm(year$W.L.~ -1 + year$ThreeProp)
  coef1[i] <- summary(O_Model1)$coefficients[1]
  pval1[i] <- summary(O_Model1)$coefficients[1,4]
  
  # effective field goal percentage
  O_Model2 <- lm(year$W.L.~ -1 + year$eFG)
  coef2[i] <- summary(O_Model2)$coefficients[1]
  pval2[i] <- summary(O_Model2)$coefficients[1,4]
}

# Show results as data frame
results <- as.data.frame(results)

rm(anova, model, offense)

# compare coefficients for the Offensive rating
cbind(coef,pval)
#compare coefficents for three point proportion
cbind(coef1,pval1)
#compare coefficents for effective field goal percentage
cbind(coef2,pval2)

# post season reg_logs
post <- read.csv("NBA-2017-18-Postseason-Game-Logs.csv", header = TRUE)
#rename W/L response variable
colnames(post)[4] <- "W"

#set binary indicator for wins
post$W <- ifelse(post$W == "W", 1, 0)

# start with full model and step down
post_model <- lm(post$X... ~ post$OREB + post$FGM + post$FGA + post$FG. + post$X3PM + post$X3PA + post$X3P. + post$FTM + post$FTA + post$FT. + post$DREB + post$AST + post$STL + post$BLK + post$TOV + post$PF + post$EFG., data = post)
summary(post_model)
post_step_backward <- step(post_model)

# start with full model and step up 
post_step_forward<-step(lm(X...~1, data = post), scope = X...~(PTS+FGM+ FGA+ FG.+ X3PM + X3PA+ FTM+FTA+FT.+OREB+DREB+REB+AST+STL+BLK+TOV+PF+EFG.), direction = "forward")

# compare forwards and backwards
summary(post_step_backward)
summary(post_step_forward )

# compare models for regular season and post season games
summary(step)

# cross validation to compare post season and regular season
# remove NA rows
reg_logs <- read.csv("NBA-2017-18-Regular-Season-Game-Logs.csv", header = TRUE)
reg_logs <- as.data.frame(reg_logs)

reg_logs <- reg_logs[complete.cases(reg_logs),]

set.seed(2019)
nsims = 1000
n = nrow(reg_logs)
sse1 = sse2 = rep(NA,nsims)
coef1 = matrix(NA, ncol = 18, nrow = nsims)
coef2 = matrix(NA, ncol = 18, nrow = nsims)

for( i in 1:nsims){
  reorder = sample(n)
  train = reg_logs[reorder[1:1000],]
  test = reg_logs[reorder[1001:n],]
  # fit1: from stepdown model from regular season games
  fit1 <- lm(W ~ OREB+FGM+FG.+X3PM+X3PA+X3P.+FTM+FTA+FT.+DREB+AST+STL+BLK+TOV+PF+EFG., data = train)
  # fit2: stepdown model from post season games
  fit2 <- lm(W~ OREB +FGM+FGA+FG.+X3PM+X3PA+FTM+FTA+FT.+DREB+AST+STL+BLK+TOV+PF+EFG., data = train)
  # fit errors
  sse1[i] = sum(test$X...-predict(fit1,new=test)^2)
  sse2[i] = sum(test$X...-predict(fit2,new=test)^2) 
  coef1[i,]=c(fit1$coef,sum(fit1$residuals^2)/fit1$df.residual)
  coef2[i,]=c(fit2$coef,sum(fit2$residuals^2)/fit2$df.residual)
}
c(mean(sse1),mean(sse2))/(n-1000)
c(summary(fit1)$sigma^2,summary(fit2)$sigma^2)


RatingModel <- lm(data$W ~ ORtg + DRtg, data = data)
summary(RatingModel)

#checking linearity assumption
plot(data$W ~ data$ORtg)
plot(data$W ~ data$DRtg)

#checking normality
hist(data$ORtg)
hist(data$DRtg)
hist(data$NRtg)

#checking for collinearity/highlighting all championship winning teams 
#possible because all championship teams had unique values for ORtg
plot(data$ORtg ~ data$DRtg, col=ifelse(data$ORtg %in% c(107.85, 109.15, 
    110.29, 106.25, 103.18, 108.45, 109.53, 110.11, 111.10, 113.43, 
    109.51, 110.24, 107.66, 113.43, 111.09, 112.18, 111.80, 116.26, 114.31),
    "red", "black"), pch=ifelse(data$ORtg %in% c(107.85, 109.15, 110.29, 
    106.25, 103.18, 108.45, 109.53, 110.11, 111.10, 113.43, 109.51, 110.24,
    107.66, 113.43, 111.09, 112.18, 111.80, 116.26, 114.31), 8, 1), 
xlab = "Defensive Rating", ylab = "Offensive Rating", 
main = "Defensive Rating vs. Offensive Rating")
abline(v = mean(data$DRtg), col="blue", lwd=1, lty=2)
abline(h = mean(data$ORtg), col="blue", lwd=1, lty=2)

# compare coefficients for the Offensive rating
cbind(coef,pval)
#compare coefficents for three point proportion
cbind(coef1,pval1)
#compare coefficents for effective field goal percentage
cbind(coef2,pval2)
```
